### ISSUE TITLE
compile time configs should be moved to runtime

### ISSUE THREAD

**Issue by chess4ever** [primait/prima_opentelemetry_ex#48]
Configuration variable depending on the environment should generally be read at runtime and not at compile time.
Right now `exclude` and `enabled` configs are read at compile time, so if the client application tries to configure such behaviours at runtime, it will not work since the default will be used but nothing breaks, so it is also difficult to find out the problem.

**Comment by cpiemontese** [comment]
Should be closed by this: https://github.com/primait/prima_opentelemetry_ex/pull/49
